---
- name: install app requirements
  hosts: site1router
  connection: local
  gather_facts: no
  tasks:

    - name: install pip
      apt:
        name: python3-pip
      become: yes

    - name: pip install requirements
      pip:
        requirements: /vagrant/requirements.txt
        executable: pip3
      become: yes